---
# Roles commonly include variables for OS specific configuration.
- name: Include OS specific vars
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Include distribution specific vars
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "{{ role_path }}/../silpion.lib/vars/os-specific/noop.yml"
  include_vars: "{{ item }}"
